remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Tatiana Vanchurina
description: "2D Artist | Vector Illustrator"
email: t.vanchurina@gmail.com
logo: /assets/images/ava.png
favicon: true
color-scheme: light
github_maintainer: drew2a

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/tatiana-vanchurina

github:
  is_project_page: false
  is_user_page: false

navigation:
  - name: "2D Artist | Vector Illustrator"
    link: /
    sublist:
      - name: Animation Art
        link: /#animation-art
      - name: Educational & Medical Illustration
        link: /#educational--medical-illustration
      - name: Surface Pattern Design
        link: /#surface-pattern-design
      - name: Packaging Illustration
        link: /#packaging-illustration
      - name: Children's Book Illustration
        link: /#childrens-book-illustration
      - name: Game Art
        link: /#game-art

  - name: Projects
    link: /projects.html
    sublist:
      - name: 'Animated series "Muffin Socks"'
        link: /projects/muffin_socks.html
      - name: 'Animated series "Avocado Couple"'
        link: /projects/avocado_couple.html
      - name: 'Animated series "Jolly Woo"'
        link: /projects/jollywoo.html
      - name: 'Visual novel "Royal Mint"'
        link: /projects/royal_mint.html
      - name: Books
        link: /projects/books.html
  - name: Sleeping cat
    link: /sleeping_cat.html
