remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Tatiana Vanchurina
description: Portfolio
email: irbiirbi9@gmail.com
logo: /assets/images/ava.png
favicon: true
color-scheme: light
github_maintainer: drew2a

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/tatiana-vanchurina-34b87352

github:
  is_project_page: false
  is_user_page: false

navigation:
  - name: Portfolio
    link: /
    sublist:
      - name: Characters
        link: /#characters
      - name: Stuff
        link: /#stuff
      - name: Locations
        link: /#locations
      - name: Vectors
        link: /#vectors
      - name: Seamless Patterns
        link: /#seamless-patterns

  - name: Projects
    link: /projects.html
    sublist:
      - name: Books
        link: /projects/books.html

  - name: Sleeping cat
    link: /sleeping_cat.html